apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: example
spec:
  provider:
    vault:
      server: "<VAULT_SERVER_URL"
      version: "v2"
      namespace: "external-secrets"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "external-secrets"
          key: "token"

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
data:
  token: <VAULT_AUTHENTICATION_TOKEN> # "root"
