apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "dynamic-external-secret"
  namespace: external-secrets
spec:
  refreshInterval: "1h"
  target:
    name: db-credentials
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: "db-credentials"