apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: example
    kind: ClusterSecretStore
  target:
    name: application-sync
  data: 
    - secretKey: PASSWORD
      remoteRef:
         key: secret
         property: PASSWORD

