apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: db-credentials
  namespace: external-secrets
spec:
  path: "/database/creds/dynamicrole"
  method: "GET"
  provider:
    server: "<VAULT_SERVER_URL>"
    auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "external-secrets"
          key: "token"
